name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - feature/tests
  pull_request:
    branches:
      - master
      - feature/tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run tests
      run: |
        pytest
